"""
Agent 7 — Sizing & Plan Agent (SPA)

Converts an approved risk decision into a fully costed, fully documented
trade plan. SPA is the last agent before execution; if it cannot build a
valid plan it discards the decision silently (with an audit record).

Core sizing logic:
  - Per-trade risk = 0.5% of current account equity (configurable)
  - shares = floor(max_risk_dollars / risk_per_share)
  - Risk per share = |entry_price - stop_price|
  - Maximum size bounded by max_symbol_concentration_pct
  - R:R floor: target = entry + (entry - stop) * 2.0  (minimum 2:1)

Cost model:
  - Commission: $0 (Alpaca)
  - SEC fee: SEC_FEE_RATE * (entry_price * shares)   [sell side only]
  - FINRA TAF: min(FINRA_TAF_RATE * shares, $8.30)   [sell side only]
  - Slippage: spread_bps/2 * entry_price / 10_000
             (widened 1.5x when execution quality is degraded)

Net expectancy:
  Pulled from the ApprovedSetupList for the signal's setup_type:
    expectancy = win_rate * avg_win - (1 - win_rate) * avg_loss
  Then reduced by total_cost_per_share.
  If net_expectancy_per_share <= 0 the plan is REJECTED.

Safety contract:
  - No averaging down (no adding to an existing position).
  - No plan without a valid stop, time_stop, and natural-language
    invalidation_reason generated by the LLM.
  - No plan with net_expectancy_per_share <= 0.
  - Never exceed per-trade risk limit.

Subscribed topics : RISK_DECISION, EXECUTION_QUALITY
Publishes         : TRADE_PLAN
"""
from __future__ import annotations

import logging
import math
from typing import Callable

from core.constants import (
    AGENT_IDS,
    FINRA_TAF_RATE,
    SEC_FEE_RATE,
)
from core.enums import Direction, RiskDecision as RiskDecisionEnum, Topic
from core.models import (
    ApprovedSetupList,
    AuditEvent,
    BusMessage,
    CostModel,
    SessionExecutionSummary,
    TradePlan,
)
from agents.base import BaseAgent
from infrastructure.message_bus import MessageBus
from infrastructure.state_store import StateStore
from infrastructure.audit_log import AuditLog

logger = logging.getLogger(__name__)

# Slippage widening factor when execution quality is degraded
_SLIPPAGE_DEGRADED_FACTOR = 1.5

# Minimum position size (in shares) — below this a plan is not worth submitting
_MIN_SHARES = 1


class SPAAgent(BaseAgent):
    """
    Agent 7 — Sizing & Plan Agent (SPA).

    Receives approved RiskDecision messages, computes position size and a
    full cost model, asks the LLM to write the invalidation reason, validates
    positive net expectancy, and publishes a TradePlan.
    """

    # ── Constructor ──────────────────────────────────────────────────────────────

    def __init__(
        self,
        bus: MessageBus,
        store: StateStore,
        audit: AuditLog,
        account_equity_fn: Callable[[], float],
        approved_setups_fn: Callable[[], ApprovedSetupList | None],
        current_execution_quality_fn: Callable[[], SessionExecutionSummary | None],
        open_positions_fn: Callable[[], list],
        config: dict | None = None,
    ) -> None:
        super().__init__(
            agent_id=AGENT_IDS[7],
            agent_name="SPAAgent",
            bus=bus,
            store=store,
            audit=audit,
            config=config,
        )
        self._account_equity_fn = account_equity_fn
        self._approved_setups_fn = approved_setups_fn
        self._current_execution_quality_fn = current_execution_quality_fn
        self._open_positions_fn = open_positions_fn

        # In-memory cache of recent validated signals keyed by signal_id.
        # SPA also subscribes to VALIDATED_SIGNAL so it can look up the full
        # candidate payload when a RISK_DECISION arrives.
        # Capped at 500 entries to avoid unbounded growth.
        self._validated_signal_cache: dict[str, dict] = {}

        # ── Config shortcuts ──────────────────────────────────────────────────
        self._per_trade_risk_pct: float = float(
            self.cfg("capital", "per_trade_risk_pct", default=0.005)
        )
        self._max_symbol_concentration_pct: float = float(
            self.cfg("risk", "max_symbol_concentration_pct", default=0.30)
        )
        self._time_stop_sec: int = int(
            self.cfg("monitoring", "max_hold_time_sec", default=300)
        )
        self._slippage_widen_threshold_bps: float = float(
            self.cfg("execution", "slippage_widen_threshold_bps", default=5.0)
        )

        # ── Last known execution quality ──────────────────────────────────────
        self._execution_quality: SessionExecutionSummary | None = None

    # ── Topic subscriptions ───────────────────────────────────────────────────

    @property
    def subscribed_topics(self) -> list[Topic]:
        return [Topic.VALIDATED_SIGNAL, Topic.RISK_DECISION, Topic.EXECUTION_QUALITY]

    # ── Main message handler ──────────────────────────────────────────────────

    async def process(self, message: BusMessage) -> None:
        topic = message.topic

        if topic == Topic.VALIDATED_SIGNAL:
            await self._handle_validated_signal_cache(message)

        elif topic == Topic.EXECUTION_QUALITY:
            await self._handle_execution_quality(message)

        elif topic == Topic.RISK_DECISION:
            await self._handle_risk_decision(message)

    # ── VALIDATED_SIGNAL cache handler ───────────────────────────────────────

    async def _handle_validated_signal_cache(self, message: BusMessage) -> None:
        """
        Cache validated signal payloads so they can be retrieved by signal_id
        when the corresponding RiskDecision arrives.  Cap at 500 entries.
        """
        signal_id = message.payload.get("signal_id")
        if signal_id:
            if len(self._validated_signal_cache) >= 500:
                # Evict the oldest entry
                oldest_key = next(iter(self._validated_signal_cache))
                del self._validated_signal_cache[oldest_key]
            self._validated_signal_cache[signal_id] = message.payload

    # ── EXECUTION_QUALITY handler ─────────────────────────────────────────────

    async def _handle_execution_quality(self, message: BusMessage) -> None:
        try:
            self._execution_quality = SessionExecutionSummary(**message.payload)
            logger.debug(
                "[SPA] Execution quality updated: avg_slippage_bps=%.2f degraded=%s",
                self._execution_quality.avg_slippage_bps,
                self._execution_quality.quality_degraded,
            )
        except Exception as exc:
            logger.warning("[SPA] Failed to parse SessionExecutionSummary: %s", exc)

    # ── RISK_DECISION handler ─────────────────────────────────────────────────

    async def _handle_risk_decision(self, message: BusMessage) -> None:
        payload = message.payload

        # Only act on approved decisions
        decision_str = payload.get("decision", "")
        try:
            decision = RiskDecisionEnum(decision_str)
        except ValueError:
            logger.warning("[SPA] Unknown decision value '%s' — ignoring", decision_str)
            return

        if decision != RiskDecisionEnum.APPROVED:
            logger.debug("[SPA] Skipping non-approved decision: %s", decision_str)
            return

        signal_id: str = payload.get("signal_id", "")
        symbol: str = payload.get("symbol", "")

        if not signal_id or not symbol:
            logger.error("[SPA] RiskDecision missing signal_id or symbol — ignoring")
            return

        # Reconstruct the CandidateSignal from the correlated ValidatedSignal
        # SPA reads the full validated signal payload from the state store,
        # which was persisted by the SignalValidationAgent.
        validated_payload = await self._fetch_validated_signal(signal_id)
        if validated_payload is None:
            logger.error(
                "[SPA] Cannot retrieve ValidatedSignal for signal_id=%s — aborting plan",
                signal_id,
            )
            return

        candidate_data = validated_payload.get("candidate", {})
        if not candidate_data:
            logger.error("[SPA] ValidatedSignal has no candidate data for signal_id=%s", signal_id)
            return

        try:
            plan = await self._build_plan(signal_id, candidate_data)
        except Exception as exc:
            logger.warning("[SPA] Failed to build TradePlan for signal_id=%s: %s", signal_id, exc)
            await self.audit.record(AuditEvent(
                event_type="TRADE_PLAN_REJECTED",
                agent=self.agent_id,
                symbol=symbol,
                details={"signal_id": signal_id, "reason": str(exc)},
            ))
            return

        if plan is None:
            return  # Rejection already logged inside _build_plan

        await self.publish(
            Topic.TRADE_PLAN,
            plan.model_dump(mode="json"),
            correlation_id=signal_id,
        )

        await self.audit.record(AuditEvent(
            event_type="TRADE_PLAN_PUBLISHED",
            agent=self.agent_id,
            symbol=symbol,
            details={
                "plan_id": plan.plan_id,
                "signal_id": signal_id,
                "shares": plan.shares,
                "entry_price": plan.entry_price,
                "stop_price": plan.stop_price,
                "target_price": plan.target_price,
                "risk_per_share": plan.risk_per_share,
                "total_risk": plan.total_risk,
                "net_expectancy_per_share": plan.net_expectancy_per_share,
                "time_stop_sec": plan.time_stop_sec,
                "invalidation_reason": plan.invalidation_reason,
            },
        ))

        logger.info(
            "[SPA] TradePlan published: plan_id=%s symbol=%s shares=%d "
            "entry=%.2f stop=%.2f target=%.2f ev/share=%.4f",
            plan.plan_id, symbol, plan.shares,
            plan.entry_price, plan.stop_price, plan.target_price,
            plan.net_expectancy_per_share,
        )

    # ── Plan construction ─────────────────────────────────────────────────────

    async def _build_plan(
        self, signal_id: str, candidate_data: dict
    ) -> TradePlan | None:
        """
        Build and return a fully validated TradePlan, or return None if any
        safety check fails (rejection already logged inside this method).
        """
        symbol: str = candidate_data.get("symbol", "")
        setup_type_str: str = candidate_data.get("setup_type", "")
        direction_str: str = candidate_data.get("direction", "")
        entry_price: float = float(candidate_data.get("entry_price", 0))
        stop_price: float = float(candidate_data.get("initial_stop", 0))
        tick_data: dict = candidate_data.get("tick_at_signal", {})
        misa_reasoning: str = candidate_data.get("reasoning", "")

        from core.enums import SetupType
        try:
            direction = Direction(direction_str)
            setup_type = SetupType(setup_type_str)
        except ValueError as exc:
            logger.error("[SPA] Invalid direction or setup_type: %s", exc)
            return None

        if entry_price <= 0 or stop_price <= 0:
            logger.warning("[SPA] Invalid entry/stop prices for %s — aborting", symbol)
            return None

        # ── Safety: no averaging down ─────────────────────────────────────────
        open_positions = self._open_positions_fn()
        if any(p.symbol == symbol for p in open_positions):
            logger.warning(
                "[SPA] %s already has an open position — AVERAGING DOWN BLOCKED", symbol
            )
            await self.audit.record(AuditEvent(
                event_type="AVERAGING_DOWN_BLOCKED",
                agent=self.agent_id,
                symbol=symbol,
                details={"signal_id": signal_id},
            ))
            return None

        equity = self._account_equity_fn()
        if equity <= 0:
            logger.error("[SPA] Account equity is zero or negative — aborting plan")
            return None

        # ── Position sizing ───────────────────────────────────────────────────
        risk_per_share = abs(entry_price - stop_price)
        if risk_per_share <= 0:
            logger.warning("[SPA] %s: entry == stop — cannot compute risk_per_share", symbol)
            return None

        max_risk_dollars = equity * self._per_trade_risk_pct
        shares_by_risk = math.floor(max_risk_dollars / risk_per_share)

        # Also cap by max symbol concentration
        max_shares_by_concentration = math.floor(
            (equity * self._max_symbol_concentration_pct) / entry_price
        )
        shares = min(shares_by_risk, max_shares_by_concentration)

        if shares < _MIN_SHARES:
            logger.warning(
                "[SPA] %s: computed shares=%d below minimum (%d) — aborting",
                symbol, shares, _MIN_SHARES,
            )
            await self.audit.record(AuditEvent(
                event_type="TRADE_PLAN_REJECTED",
                agent=self.agent_id,
                symbol=symbol,
                details={
                    "signal_id": signal_id,
                    "reason": f"shares={shares} below minimum {_MIN_SHARES}",
                    "risk_per_share": risk_per_share,
                    "max_risk_dollars": max_risk_dollars,
                },
            ))
            return None

        # ── Target price (minimum 2:1 R:R) ────────────────────────────────────
        risk_amount = abs(entry_price - stop_price)
        if direction == Direction.LONG:
            target_price = entry_price + risk_amount * 2.0
        else:
            target_price = entry_price - risk_amount * 2.0

        # ── Cost model ────────────────────────────────────────────────────────
        spread_bps = float(tick_data.get("spread_bps", 0))
        cost_model = self._compute_cost_model(entry_price, shares, spread_bps)

        # ── Net expectancy ────────────────────────────────────────────────────
        net_ev = self._compute_net_expectancy(setup_type, cost_model)
        if net_ev is None:
            logger.warning(
                "[SPA] %s: setup '%s' not in approved setups — cannot compute EV, aborting",
                symbol, setup_type_str,
            )
            await self.audit.record(AuditEvent(
                event_type="TRADE_PLAN_REJECTED",
                agent=self.agent_id,
                symbol=symbol,
                details={
                    "signal_id": signal_id,
                    "reason": f"setup_type '{setup_type_str}' not in approved setups",
                },
            ))
            return None

        if net_ev <= 0:
            logger.warning(
                "[SPA] %s: net_expectancy_per_share=%.4f <= 0 — REJECTING plan",
                symbol, net_ev,
            )
            await self.audit.record(AuditEvent(
                event_type="TRADE_PLAN_REJECTED",
                agent=self.agent_id,
                symbol=symbol,
                details={
                    "signal_id": signal_id,
                    "reason": f"non-positive net expectancy: {net_ev:.4f}",
                },
            ))
            return None

        # ── LLM: invalidation reason ──────────────────────────────────────────
        invalidation_reason = await self._llm_invalidation_reason(
            symbol=symbol,
            setup_type=setup_type_str,
            direction=direction_str,
            entry_price=entry_price,
            stop_price=stop_price,
            target_price=target_price,
            tick_data=tick_data,
            misa_reasoning=misa_reasoning,
        )

        # ── Worst-case slippage ───────────────────────────────────────────────
        worst_case_slippage = cost_model.estimated_slippage * shares

        # ── Build TradePlan (Pydantic validates stop > 0 and EV > 0) ──────────
        try:
            plan = TradePlan(
                signal_id=signal_id,
                symbol=symbol,
                direction=direction,
                entry_price=entry_price,
                stop_price=stop_price,
                target_price=target_price,
                shares=shares,
                time_stop_sec=self._time_stop_sec,
                invalidation_reason=invalidation_reason,
                cost_model=cost_model,
                net_expectancy_per_share=net_ev,
                account_equity_at_plan=equity,
                risk_per_share=risk_per_share,
                total_risk=risk_per_share * shares,
                worst_case_slippage=worst_case_slippage,
            )
        except ValueError as exc:
            # TradePlan model_validators will catch non-positive EV or missing stop
            logger.error("[SPA] TradePlan construction rejected by model validator: %s", exc)
            await self.audit.record(AuditEvent(
                event_type="TRADE_PLAN_REJECTED",
                agent=self.agent_id,
                symbol=symbol,
                details={"signal_id": signal_id, "reason": str(exc)},
            ))
            return None

        return plan

    # ── Cost model computation ────────────────────────────────────────────────

    def _compute_cost_model(
        self, entry_price: float, shares: int, spread_bps: float
    ) -> CostModel:
        """
        Compute all transaction costs for the round trip.

        SEC fee and FINRA TAF are sell-side only.
        Slippage estimate is widened if execution quality is degraded.
        """
        # Commission: Alpaca charges $0
        commission = 0.0

        # Sell-side regulatory fees (modelled even for buys — they apply on exit)
        sale_proceeds = entry_price * shares
        sec_fee = SEC_FEE_RATE * sale_proceeds

        finra_taf = min(FINRA_TAF_RATE * shares, 8.30)

        # Slippage: half-spread estimate, widened if execution quality degraded
        normal_slippage_per_share = (spread_bps / 2) * entry_price / 10_000

        quality = self._current_execution_quality_fn()
        degraded = (
            quality is not None
            and (
                quality.quality_degraded
                or quality.avg_slippage_bps > self._slippage_widen_threshold_bps
            )
        )
        slippage_factor = _SLIPPAGE_DEGRADED_FACTOR if degraded else 1.0
        estimated_slippage = normal_slippage_per_share * slippage_factor

        return CostModel(
            commission=commission,
            sec_fee=sec_fee,
            finra_taf=finra_taf,
            estimated_slippage=estimated_slippage,
        )

    # ── Net expectancy computation ────────────────────────────────────────────

    def _compute_net_expectancy(
        self, setup_type, cost_model: CostModel
    ) -> float | None:
        """
        Retrieve win_rate, avg_win, avg_loss from the ApprovedSetupList and
        compute the net expectancy per share after subtracting total costs.

        Returns None if the setup is not found in the approved list.
        """
        approved = self._approved_setups_fn()
        if approved is None:
            return None

        setup = approved.get_setup(setup_type)
        if setup is None:
            return None

        # Kelly / EV formula
        gross_ev = setup.win_rate * setup.avg_win - (1 - setup.win_rate) * setup.avg_loss

        # Subtract round-trip cost per share
        net_ev = gross_ev - cost_model.total_cost_per_share

        return net_ev

    # ── LLM: natural language invalidation reason ─────────────────────────────

    async def _llm_invalidation_reason(
        self,
        *,
        symbol: str,
        setup_type: str,
        direction: str,
        entry_price: float,
        stop_price: float,
        target_price: float,
        tick_data: dict,
        misa_reasoning: str,
    ) -> str:
        """
        Ask the LLM to generate a single, precise natural-language sentence
        describing the specific price action condition that would invalidate
        this trade thesis — i.e., the earliest observable signal that the
        trade idea is wrong.

        Returns the generated string, or a safe fallback if the LLM is unavailable.
        """
        system_prompt = (
            "You are the Sizing & Plan Agent (SPA) for an autonomous equity day-trading system. "
            "Your job is to write a single, specific natural-language invalidation condition "
            "for a trade: the exact price action event that would prove the trade thesis wrong. "
            "Be precise: name a price level, a candle behaviour, or an indicator crossing. "
            "Do not use vague language like 'if the trade goes against us'. "
            "Respond with a single sentence only. No JSON. No bullet points."
        )

        risk_per_share = abs(entry_price - stop_price)
        user_message = f"""
Trade details:
  Symbol:       {symbol}
  Setup type:   {setup_type}
  Direction:    {direction}
  Entry price:  ${entry_price:.2f}
  Stop price:   ${stop_price:.2f}  (risk/share = ${risk_per_share:.2f})
  Target price: ${target_price:.2f}
  Spread (bps): {tick_data.get('spread_bps', 0):.2f}

MiSA detection reasoning:
{misa_reasoning or '(not provided)'}

Write one sentence: "This trade is wrong if..."
"""

        try:
            text = await self.llm_call(system_prompt, user_message, max_tokens=128)
            reason = text.strip()
            if not reason:
                raise ValueError("Empty response from LLM")
            # Ensure it starts naturally
            if not reason.lower().startswith("this trade"):
                reason = f"This trade is wrong if {reason.lstrip('.').strip()}"
            return reason
        except Exception as exc:
            logger.warning("[SPA] LLM invalidation reason failed: %s — using fallback", exc)
            # Deterministic fallback
            if direction.lower() == "long":
                return (
                    f"This trade is wrong if {symbol} closes a 1-minute bar below "
                    f"${stop_price:.2f} on above-average volume, indicating sellers have "
                    f"overwhelmed the {setup_type} structure."
                )
            else:
                return (
                    f"This trade is wrong if {symbol} closes a 1-minute bar above "
                    f"${stop_price:.2f} on above-average volume, indicating buyers have "
                    f"reclaimed the {setup_type} level."
                )

    # ── Signal cache lookup ───────────────────────────────────────────────────

    async def _fetch_validated_signal(self, signal_id: str) -> dict | None:
        """
        Retrieve the ValidatedSignal payload from the in-memory cache that was
        populated when the VALIDATED_SIGNAL message was first received.

        Returns None if the signal has not been seen (e.g., arrived out of order
        or the cache was full and the entry was evicted).
        """
        payload = self._validated_signal_cache.get(signal_id)
        if payload is None:
            logger.warning(
                "[SPA] ValidatedSignal not found in cache for signal_id=%s — "
                "message may have arrived before SPA subscribed or cache evicted it",
                signal_id,
            )
        return payload
